@startuml
start
    :Carregar lista de funcionários;
    :Escolher ação;
    if (Cadastrar ?) then (Sim)
        :Preencher campos de cadastro;
        elseif (Atualizar ?) then (Sim)
            :Preencher campos que deseja atualizar;
        elseif (Excluir ?) then (Sim)
            :Selecionar o usuário a ser removido;
        else (Não)
            stop
    endif
    :Validar informações alteradas;
    :Salvar alterações;
stop
@enduml