@startuml
start
        :Informar email da conta;
        if (Email cadastrado ?) then (Sim)
        :Enviar um email com instruções para mudança de senha;
        else
        stop
        endif
        stop
@enduml