@startuml
start
while (Deseja cadastrar usuário ?) is (Sim)
    :Informar dados;
    if (Dados válidos ?) then (Sim)
        :Confirmar cadastro;
    else (Não)
        :Negar cadastro;
    endif
    endwhile (Não)
    stop
    @enduml