@startuml
start
if (Feedback de produto ?) then (Sim)
        :Avaliar produto (gostei ou não gostei);
else (Não)
        if (Feedback de loja ?) then (Sim)
                :Escrever feedback;
                :Dar nota à loja;
                :Enviar feedback;
        else (Não)
        endif
endif
stop
@enduml