@startuml
start
if (Feedback de loja ?) then (Sim)
    :Selecionar a loja;
    if (Loja tem feebacks ?) then (Sim)
        :Exibir lista de feebacks;
        :Selecionar o feedback;
        if (Reportar feedback ?) then (Sim)
            :Enviar o feedback aos administradores do site;
            stop
        else (Não)
            :Visualizar;
            stop
        endif
    else (Não)
        stop
    endif
else (Não)
    if (Feedback de produto ?) then (Sim)
        :Visualizar avaliações do produto;
        stop
    else (Não)
        stop
    endif
endif
@enduml