@startuml
start
:Selecionar ação;
if (Excluir ?) then (Sim)
    :Confirmar exclusão;
    if (Confirmou ?) then (Sim)
        :Excluir conta;
        stop
    else (Não)
        stop
    endif
else (Não)
    if (Atualizar ?) then (Sim)
        :Alterar as informações desejadas;
        :Salvar alterações;
        stop
    else (Não)
        stop
    endif
endif
@enduml