@startuml
start
:Carregar lista de funcionários;
:Escolher ação;
if (Cadastrar ?) then (Sim)
    :Preencher campos de cadastro;
    :Verificar informações;
    if (Informações válidas ?) then (Sim)
        :Confirmar cadastro;
    else (Não)
    endif
else (Não)
    if (Atualizar ?) then (Sim)
        :Preencher campos que deseja atualizar;
        :Validar informações alteradas;
        :Salvar alterações;
    else (Não)
        if (Excluir ?) then (Sim)
            :Selecionar o funcionário a ser removida;
            :Confirmar exclusão;
        else (Não)
        endif
    endif
endif
stop
@enduml