@startuml
start
:Informar login e senha;
if (Autenticação falhou ?) then (Sim)
    if (Esqueceu a senha ?) then (Sim)
        :Enviar email de reconfiguração de senha;
        :Redefinir senha;
    else (Não)
        :Exibir mensagem de erro;
    endif
else (Não)
    :Iniciar sessão;
endif
stop
@enduml